#!/usr/bin/python

import subprocess
result = subprocess.check_output(["ls"])
dir = input("enter dir name:")
makedir = ["mkdir"]
makedir.append(dir)
subprocess.run(makedir)



dd = result.decode("utf-8")
outputs = dd.split("\n")
for output in outputs:
    if output == "ryan":
        continue
    elif output == "":
        continue

    else:
        command = ["cp","-r"]
        command.append(output)
        print(output +" moved to " + dir)
        command.append(dir +"/")
        subprocess.run(command)

zip = ["gzip","-r" ,"-1","-9"]
zip.append(dir)
print("compressing " + dir +"/")
subprocess.run(zip)
print("all done")
